sudo: false

env:
  global:
    - PROJECT_NAME=${PWD##*/}
    - NINJA_STATUS="[%p %u/%t@%o %r]"

matrix:
  include:
    # C++ Debug
    - language: cpp
      os: osx
      env:
        - BUILD_TYPE=Debug
      before_install:
        - ./scripts/install_requirements.sh
      script:
        - ./scripts/build_lib.sh
    # C++ Release
    - language: cpp
      os: osx
      env:
        - BUILD_TYPE=Release
      before_install:
        - ./scripts/install_requirements.sh
      script:
        - ./scripts/build_lib.sh
    # Node
    - language: node_js
      node_js: 8
      env:
        - secure: "F/wjnU5PXlUsD+E7YXul2nJLY+m2thugxHKGs7cKmiNO5FZNOKkclpmkgXN3wfLhHGDAvCF+cI/TqTX3AImIIKfdtMIa55B3wsRXcMeE2UckuhCOV+GCU7UWDmAEerK6TA2Trq393uARGwnB4GmYTZfLZjMGyTR8PdE7LWfboRIkffuzFAOhTX7wnQGQYJo21Htd0912IVPNHcVjMK0Ok8gwrapeNHAdED0XoUvMf+g5UcMzE4ayZYM7jIgc/NKHSOd4zZw56ycHKal5U677bG8k5pUE4SRnMl0iafsRGoTKDs8gJhO5F5zb4NKvCyPzhMUnDqSVMRCydWsFjIyzfsuOabbScmWl4dG2HrojmfJ6k8BuaMxTNWIxGgw5CrM+mdFilphypfZyz0jcGfBBPjVYFzllY+QznOB/w/RVTd32FBKDsXIZL5gmYZglVckm0h1dYz20R1U+kQHLGrn056iNluDWGrdQgQ2U6wMULiN3xM+x3n0bgRn2XhLyV0hxIzqFVuJgW6hiK5p2TssjpJUBOlYaPxr51LkeKsHil5zODseuDIWK9VL9LgV7CEinc9ssXgdd7vXtJw/w8mikov6wXE4L5QQDX5E9NjoGPKk/h7zxL2EUvRDMQuFaEkRyi99/O2MchI1F61qAk29rIr/7pzjFdNKI6zr/TxvfPY4="
      before_install:
        - |
          yarn --cwd js install \
            --pure-lockfile \
            --non-interactive
      script:
        - yarn --cwd js test:cov
        - yarn --cwd js build
      after_success:
        - source ./scripts/set_npm_package_version.sh
      deploy:
        provider: script
        # https://blog.travis-ci.com/2018-04-11-how_to_publish_node_js_packages_with_travis_ci_and_packagecloud
        script: npm config set '//registry.npmjs.org/:_authToken' ${NPM_AUTH_TOKEN} && npm publish js
        skip_cleanup: true
        on:
          condition: $ROCKETS_CLIENT_VERSION != ''
          branch: master
    # Python 3.5
    - language: python
      python: 3.5
      install:
        - cd python
        - pip install .
        - pip install tox-travis
      script:
        - tox
    # Python 3.6
    - language: python
      python: 3.6
      install:
        - cd python
        - pip install .
        - pip install tox-travis
      script:
        - tox
      before_deploy:
        - pip install twine
      after_success:
        - export ROCKETS_PY_DO_DEPLOY=`../scripts/check_version.py`
      deploy:
        provider: pypi
        user: bbp.opensource
        password:
          secure: "G4M0GPsX3UJ2KKxUlZiBcUp648aBfHV0IItPK1ak5nJ5bMB3rbqB/divDfbm0L+gvjZcPtKvHQ3yZmNLwBJO95L7/WmEcxKPYUdi3YfZV6Kd4sq/hrDsFBYqHDwk6/UCKQGIrFz1LD+13ch4RIx9QhiZZC27ismORGK9KQA5ZAo+DnH55lY2AAg3Gb1sr1RnSzmKCKOmeTTESYLexAIEkE7nZ/4dT89KvlpgWdOcpJs2Mywp4t/v5EoLdGo7RbkhkTSMLfU6NaWXkl9ZC52ca34sIWevqoKiYcLLg8+6DKeSwMLgxHkh0w0VnTJGEs28NirKyQvd3Nc/OZ2jK92vWLuh2jDGkRO7m9tWXUVK2rN21rfhTK8qVA1mi2sgOSYN8F7ZGpxbvavyB9lyB+6xnCwITWGxAVIRkvxhanukc1jvupq4PrxuMDyPLDIol2nd/WXbteApePbrvHQ7G5622b2E8lXz4yBr24uhStHu8RGyaUTCsnsGdfCBJqlxv4miNnOcYkYuZGfToHMs53+m8xM4pS2YD5Z59fgykLp1QUu496XUvCh0loRuZvhQoizlBLjx1Eqg68uqi56ke3tEUC0oOIhZmoRHlXb6j9NlVIOC0MQOctfy4lBu43ODzrtmuWwjpyeCxmBUAQ2BmCqIS2Uzs8qr+Di0ixjhyK3feS0="
        on:
          condition: $ROCKETS_PY_DO_DEPLOY != ''
          branch: master
    # Python 3.7
    - language: python
      # https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-425867404
      dist: xenial
      sudo: true
      python: 3.7
      install:
        - cd python
        - pip install .
        - pip install tox-travis
      script:
        - tox

notifications:
  email:
    on_success: never
