sudo: false

env:
  global:
    - PROJECT_NAME=${PWD##*/}
    - NINJA_STATUS="[%p %u/%t@%o %r]"

matrix:
  include:
    # C++ Debug
    - language: cpp
      os: osx
      env:
        - BUILD_TYPE=Debug
      before_install:
        - ./scripts/install_requirements.sh
      script:
        - ./scripts/build_lib.sh
    # C++ Release
    - language: cpp
      os: osx
      env:
        - BUILD_TYPE=Release
      before_install:
        - ./scripts/install_requirements.sh
      script:
        - ./scripts/build_lib.sh
    # Node
    - language: node_js
      node_js: 8
      env:
        - secure: "F/wjnU5PXlUsD+E7YXul2nJLY+m2thugxHKGs7cKmiNO5FZNOKkclpmkgXN3wfLhHGDAvCF+cI/TqTX3AImIIKfdtMIa55B3wsRXcMeE2UckuhCOV+GCU7UWDmAEerK6TA2Trq393uARGwnB4GmYTZfLZjMGyTR8PdE7LWfboRIkffuzFAOhTX7wnQGQYJo21Htd0912IVPNHcVjMK0Ok8gwrapeNHAdED0XoUvMf+g5UcMzE4ayZYM7jIgc/NKHSOd4zZw56ycHKal5U677bG8k5pUE4SRnMl0iafsRGoTKDs8gJhO5F5zb4NKvCyPzhMUnDqSVMRCydWsFjIyzfsuOabbScmWl4dG2HrojmfJ6k8BuaMxTNWIxGgw5CrM+mdFilphypfZyz0jcGfBBPjVYFzllY+QznOB/w/RVTd32FBKDsXIZL5gmYZglVckm0h1dYz20R1U+kQHLGrn056iNluDWGrdQgQ2U6wMULiN3xM+x3n0bgRn2XhLyV0hxIzqFVuJgW6hiK5p2TssjpJUBOlYaPxr51LkeKsHil5zODseuDIWK9VL9LgV7CEinc9ssXgdd7vXtJw/w8mikov6wXE4L5QQDX5E9NjoGPKk/h7zxL2EUvRDMQuFaEkRyi99/O2MchI1F61qAk29rIr/7pzjFdNKI6zr/TxvfPY4="
      before_install:
        - |
          yarn --cwd js install \
            --pure-lockfile \
            --non-interactive
      script:
        - yarn --cwd js test:cov
        - yarn --cwd js build
      after_success:
        - source ./scripts/set_npm_package_version.sh
      deploy:
        provider: script
        # https://blog.travis-ci.com/2018-04-11-how_to_publish_node_js_packages_with_travis_ci_and_packagecloud
        script: npm config set '//registry.npmjs.org/:_authToken' ${NPM_AUTH_TOKEN} && npm publish js
        skip_cleanup: true
        on:
          condition: $ROCKETS_CLIENT_VERSION != ''
          branch: master
    # Python 3.5
    - language: python
      python: 3.5
      install:
        - cd python
        - pip install .
        - pip install tox-travis
      script:
        - tox
    # Python 3.6
    - language: python
      python: 3.6
      install:
        - cd python
        - pip install .
        - pip install tox-travis
      script:
        - tox
      before_deploy:
        - pip install twine
      after_success:
        - export ROCKETS_PY_DO_DEPLOY=`../scripts/check_version.py`
      deploy:
        provider: pypi
        user: nachbaur
        password:
          secure: "P9qTrM1S+QdKuxiyQoqEGon6979z/1Yvnd5JcAQXEWG68KhVsYWhkOzj6qRxYro/k2bnHM2ijKJ6UeB9m3TW6DyCnro3vyDpEYC0QezYPX2dUcC93814BsmlWEjD5lW7Ol8yoI7GyffC7CQ0ZUxdQjObQdFm3RE2ywY8Vq98aJfU/rJizaAhtA0fWGK7J8b2fC0HCjbP8RJyivUq+aqmgRXglEKhfwiLPO7G45i20mxUBD1zJw40U1sWQvYjeIoRoLCpBnWf5lOWTJLyUBOVjUWxvrwkGNf2kejkYVAXD7+M8rr7FW/6NAI+4KQYQTueZcYT6GoBLQHWZYDGwVV8C8CAjMpzcOzR1rQrRDPWwccnAu2zvBE4cZEhjo+Zkt9GOuwAoGCaLJ6JuSZ4/YnqC6+e8Qh4KH2g4EQ5f467AfyxrcSN/SusVtoPO9T2Wee6XiRxzEge0hIu/SKOaPvCqXrRYavFDGfVgmBRTok7cl4PzXUUTE4k+zPHWhutBW29dNYY9iWDfaCClKw+9qSAqytVJEBH5o7Uw1ye/LCWhg9FdwabYc6LJ623a7QGoKKwntmZMiWDOl8+/rWdAtgXHy9wZ4u15gy9i14ak1+D2vu7jvFGC9kEaZvhAFJFM/S1/Oo3Woidz2qxv/DhbXnAGLLgb5hTdgb6XFewTzhvjtM="
        on:
          condition: $ROCKETS_PY_DO_DEPLOY != ''
          branch: master
    # Python 3.7
    - language: python
      # https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-425867404
      dist: xenial
      sudo: true
      python: 3.7
      install:
        - cd python
        - pip install .
        - pip install tox-travis
      script:
        - tox

notifications:
  email:
    on_success: never
