sudo: false

env:
  global:
    - PROJECT_NAME=${PWD##*/}
    - NINJA_STATUS="[%p %u/%t@%o %r]"

matrix:
  include:
    # C++ Debug
    - language: cpp
      os: osx
      env:
        - BUILD_TYPE=Debug
      before_install:
        - ./scripts/install_requirements.sh
      script:
        - ./scripts/build_lib.sh
    # C++ Release
    - language: cpp
      os: osx
      env:
        - BUILD_TYPE=Release
      before_install:
        - ./scripts/install_requirements.sh
      script:
        - ./scripts/build_lib.sh
    # Node
    - language: node_js
      node_js: 8
      env:
        - secure: "F/wjnU5PXlUsD+E7YXul2nJLY+m2thugxHKGs7cKmiNO5FZNOKkclpmkgXN3wfLhHGDAvCF+cI/TqTX3AImIIKfdtMIa55B3wsRXcMeE2UckuhCOV+GCU7UWDmAEerK6TA2Trq393uARGwnB4GmYTZfLZjMGyTR8PdE7LWfboRIkffuzFAOhTX7wnQGQYJo21Htd0912IVPNHcVjMK0Ok8gwrapeNHAdED0XoUvMf+g5UcMzE4ayZYM7jIgc/NKHSOd4zZw56ycHKal5U677bG8k5pUE4SRnMl0iafsRGoTKDs8gJhO5F5zb4NKvCyPzhMUnDqSVMRCydWsFjIyzfsuOabbScmWl4dG2HrojmfJ6k8BuaMxTNWIxGgw5CrM+mdFilphypfZyz0jcGfBBPjVYFzllY+QznOB/w/RVTd32FBKDsXIZL5gmYZglVckm0h1dYz20R1U+kQHLGrn056iNluDWGrdQgQ2U6wMULiN3xM+x3n0bgRn2XhLyV0hxIzqFVuJgW6hiK5p2TssjpJUBOlYaPxr51LkeKsHil5zODseuDIWK9VL9LgV7CEinc9ssXgdd7vXtJw/w8mikov6wXE4L5QQDX5E9NjoGPKk/h7zxL2EUvRDMQuFaEkRyi99/O2MchI1F61qAk29rIr/7pzjFdNKI6zr/TxvfPY4="
      before_install:
        - |
          yarn --cwd js install \
            --pure-lockfile \
            --non-interactive
      script:
        - yarn --cwd js test:cov
        - yarn --cwd js build
      before_deploy:
        - source ./scripts/set_npm_package_version.sh
      deploy:
        provider: script
        # https://blog.travis-ci.com/2018-04-11-how_to_publish_node_js_packages_with_travis_ci_and_packagecloud
        script: npm config set '//registry.npmjs.org/:_authToken' ${NPM_AUTH_TOKEN} && npm publish js
        skip_cleanup: true
        on:
          condition: $ROCKETS_CLIENT_VERSION != ''
          branch: master
    # Python 3.5
    - language: python
      python: 3.5
      install:
        - cd python
        - pip install .
        - pip install tox-travis
      script:
        - tox
    # Python 3.6
    - language: python
      python: 3.6
      install:
        - cd python
        - pip install .
        - pip install tox-travis
      script:
        - tox
      before_deploy:
        - pip install twine
      deploy:
        provider: pypi
        user: nachbaur
        password:
          secure: QT9y2YUvHLKhT5Tn8P23REtj8yeyxtmsSymr2IG0oqBn4sfmQbEpf7GO/NYiK1h+XQwh/h9iLSvqNXYtNc/hGJotP/6Jw0JXVrkI3tqepvQY0X0AzJATX1A2ioI1q09+SJQXgEdaDZj7Dafy0vyj+nIK+Ig1zjrb1wbv89EvpVi/QMh825tQPKlZk/Y7kOyJVWWqWQOuKxSfcc4suqiPEUplUFnOXtLJZr+Q5eNX2BcaiTmlzJ+IasVZYIZUatHTiDrL5j35VnXRYfGfn+CBp/CzfJBqPMKtzk+QJwla3UYYjreG4Z35xSHR83/ErYE3GOCFrmsIZ/fnu0cMMbMzQ6kz/DhblTiPqwO+clhqZlMqkpzV2WILLZsB19tld7hNQhBLP9W2qLnMg/2rWMfuqk4sqOgMBXzbuBUSAGKZLXXXe8W0uoVbRhIeh9Kf6CKTb+SXDPh8zxsuLpgdazultK2hXQcRIIf4NEFvzKlC+12+OVtuFkeKtSrUPSAcwlWNH28aJ/URuKMK7RjkqC5ATJrdtTmg1T5FQUA2Hf+fv7vHAQnAPM8gp2lD37MG34qRkhbc1icMCxc62mJ14atwgLk5jKqOAmKjV7EIHT4bZhtn0uyukWQYUIu5NaNswvHhHR5XyJbQMjZJ3dSGN/UJNpZKdXXsDHFpH/AwqYf8HA8=
        on:
          tags: true
          branch: master
    # Python 3.7
    - language: python
      # https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-425867404
      dist: xenial
      sudo: true
      python: 3.7
      install:
        - cd python
        - pip install .
        - pip install tox-travis
      script:
        - tox

notifications:
  email:
    on_success: never
